## 读取数据

In [76]:
import pandas as pd

ori_data = pd.read_excel('../data/data_A08.xlsx')
ori_data.head()

,个人编码,一天去两家医院的天数,就诊的月数,月就诊天数_MAX,月就诊天数_AVG,月就诊医院数_MAX,月就诊医院数_AVG,就诊次数_SUM,月就诊次数_MAX,月就诊次数_AVG,月统筹金额_MAX,月统筹金额_AVG,月药品金额_MAX,月药品金额_AVG,医院_就诊天数_MAX,医院_就诊天数_AVG,医院_统筹金_MAX,医院_统筹金_AVG,医院_药品_MAX,医院_药品_AVG,医院编码_NN,顺序号_NN,交易时间DD_NN,交易时间YYYY_NN,交易时间YYYYMM_NN,住院天数_SUM,个人账户金额_SUM,统筹支付金额_SUM,ALL_SUM,可用账户报销金额_SUM,药品费发生金额_SUM,药品费自费金额_SUM,药品费申报金额_SUM,贵重药品发生金额_SUM,中成药费发生金额_SUM,中草药费发生金额_SUM,检查费发生金额_SUM,检查费自费金额_SUM,检查费申报金额_SUM,贵重检查费金额_SUM,治疗费发生金额_SUM,治疗费自费金额_SUM,治疗费申报金额_SUM,手术费发生金额_SUM,手术费自费金额_SUM,手术费申报金额_SUM,床位费发生金额_SUM,床位费申报金额_SUM,医用材料发生金额_SUM,高价材料发生金额_SUM,医用材料费自费金额_SUM,成分输血申报金额_SUM,其它发生金额_SUM,其它申报金额_SUM,一次性医用材料申报金额_SUM,起付线标准金额_MAX,起付标准以上自负比例金额_SUM,医疗救助个人按比例负担金额_SUM,最高限额以上金额_SUM,基本统筹基金支付金额_SUM,公务员医疗补助基金支付金额_SUM,城乡救助补助金额_SUM,基本个人账户支付_SUM,非账户支付金额_SUM,本次审批金额_SUM,补助审批金额_SUM,医疗救助医院申请_SUM,残疾军人补助_SUM,民政救助补助_SUM,城乡优抚补助_SUM,出院诊断病种名称_NN,出院诊断LENTH_MAX,药品在总金额中的占比,个人支付的药品占比,检查总费用在总金额占比,个人支付检查费用占比,治疗费用在总金额占比,个人支付治疗费用占比,BZ_民政救助,BZ_城乡优抚,是否挂号,RES
0,352120000000000,0,6,7,5.666667,3,2.166667,34,7,5.666667,3501.18,2541.293333,3901.45,2695.291667,20,11.333333,7553.00,5082.586667,8522.57,5390.583333,3,69,34,1,6,0,1970.99,15247.76,17218.75,1868.06,16171.75,68.93,15929.04,1984.60,4776.49,0.0,875.0,0.0,875.0,0,128.0,0.0,128.0,0,0,0.0,0.0,0.0,10.00,0.0,0.0,0,34.0,0,10.00,0.0,1694.28,0.0,0.0,15247.76,0.0,0.0,228.80,1742.19,16942.04,0.0,0.0,0.0,0.0,0.0,4,29.0,0.939194,0.004262,0.050817,0.0,0.007434,0.0,0,0,1,0
1,352120000000000,0,6,4,2.500000,2,1.333333,15,4,2.500000,2217.66,1637.358333,2449.13,1783.153333,13,7.500000,9500.07,4912.075000,10309.64,5349.460000,2,64,15,1,6,0,1371.57,9824.15,11195.72,1339.67,10698.92,31.90,10418.95,2264.73,1132.45,0.0,345.0,0.0,345.0,0,150.0,0.0,150.0,0,0,0.0,0.0,0.0,1.80,0.0,0.0,0,0.0,0,1.80,0.0,1091.60,0.0,0.0,9824.15,0.0,0.0,199.50,1172.07,10915.75,0.0,0.0,0.0,0.0,0.0,3,20.0,0.955626,0.002982,0.030815,0.0,0.013398,0.0,0,0,1,0
2,352120000000000,8,6,8,6.166667,3,2.166667,45,9,7.500000,3360.55,2583.053333,3302.06,2368.528333,23,15.000000,9161.73,5166.106667,10760.51,4737.056667,3,102,37,1,6,0,2637.20,15498.32,18135.52,2621.28,14211.17,4.72,13926.88,0.00,3762.15,0.0,0.0,0.0,0.0,0,3538.0,0.0,3538.0,0,0,0.0,75.0,75.0,300.15,0.0,0.0,0,11.2,0,300.15,0.0,2341.71,0.0,0.0,15498.32,0.0,0.0,234.00,2403.20,17840.03,0.0,0.0,0.0,0.0,0.0,4,29.0,0.783610,0.000332,0.000000,0.0,0.195087,0.0,0,0,0,0
3,352120000000000,0,6,6,3.666667,2,1.833333,23,6,3.833333,3030.61,2057.720000,1500.12,1048.730000,17,11.500000,11622.17,6173.160000,5504.60,3146.190000,2,56,22,1,6,0,1373.06,12346.32,13719.38,1371.90,6292.38,1.16,6291.22,0.00,5075.85,0.0,0.0,0.0,0.0,0,7427.0,0.0,7427.0,0,0,0.0,0.0,0.0,0.00,0.0,0.0,0,0.0,0,0.00,0.0,1371.90,0.0,0.0,12346.32,0.0,0.0,73.34,1299.72,13718.22,0.0,0.0,0.0,0.0,0.0,5,16.0,0.458649,0.000184,0.000000,0.0,0.541351,0.0,0,0,0,0
4,352120000000000,0,6,5,4.333333,1,1.000000,26,5,4.333333,2332.45,2196.315000,2563.26,2417.923333,26,26.000000,13177.89,13177.890000,14507.54,14507.540000,1,64,26,1,6,0,1569.65,13177.89,14747.54,1565.06,14507.54,4.59,14402.13,2367.68,3678.72,0.0,0.0,0.0,0.0,0,240.0,0.0,240.0,0,0,0.0,0.0,0.0,0.00,0.0,0.0,0,0.0,0,0.00,0.0,1464.24,0.0,0.0,13177.89,0.0,0.0,64.00,1505.65,14642.13,0.0,0.0,0.0,0.0,0.0,2,33.0,0.983726,0.000316,0.000000,0.0,0.016274,0.0,0,0,0,0

## 评估数据
评估数据主要从两个方面进行：结构和内容，即整齐度和干净度。数据的结构性问题指不符合“每列是一个变量，每行是一个观察值，每个单元格是一个值”这三个标准，数据的内容性问题包括存在丢失数据、重复数据、无效数据等

### 评估数据整齐度

In [77]:
pd.set_option("display.max_columns",82)
ori_data.sample(10)

,个人编码,一天去两家医院的天数,就诊的月数,月就诊天数_MAX,月就诊天数_AVG,月就诊医院数_MAX,月就诊医院数_AVG,就诊次数_SUM,月就诊次数_MAX,月就诊次数_AVG,月统筹金额_MAX,月统筹金额_AVG,月药品金额_MAX,月药品金额_AVG,医院_就诊天数_MAX,医院_就诊天数_AVG,医院_统筹金_MAX,医院_统筹金_AVG,医院_药品_MAX,医院_药品_AVG,医院编码_NN,顺序号_NN,交易时间DD_NN,交易时间YYYY_NN,交易时间YYYYMM_NN,住院天数_SUM,个人账户金额_SUM,统筹支付金额_SUM,ALL_SUM,可用账户报销金额_SUM,药品费发生金额_SUM,药品费自费金额_SUM,药品费申报金额_SUM,贵重药品发生金额_SUM,中成药费发生金额_SUM,中草药费发生金额_SUM,检查费发生金额_SUM,检查费自费金额_SUM,检查费申报金额_SUM,贵重检查费金额_SUM,治疗费发生金额_SUM,治疗费自费金额_SUM,治疗费申报金额_SUM,手术费发生金额_SUM,手术费自费金额_SUM,手术费申报金额_SUM,床位费发生金额_SUM,床位费申报金额_SUM,医用材料发生金额_SUM,高价材料发生金额_SUM,医用材料费自费金额_SUM,成分输血申报金额_SUM,其它发生金额_SUM,其它申报金额_SUM,一次性医用材料申报金额_SUM,起付线标准金额_MAX,起付标准以上自负比例金额_SUM,医疗救助个人按比例负担金额_SUM,最高限额以上金额_SUM,基本统筹基金支付金额_SUM,公务员医疗补助基金支付金额_SUM,城乡救助补助金额_SUM,基本个人账户支付_SUM,非账户支付金额_SUM,本次审批金额_SUM,补助审批金额_SUM,医疗救助医院申请_SUM,残疾军人补助_SUM,民政救助补助_SUM,城乡优抚补助_SUM,出院诊断病种名称_NN,出院诊断LENTH_MAX,药品在总金额中的占比,个人支付的药品占比,检查总费用在总金额占比,个人支付检查费用占比,治疗费用在总金额占比,个人支付治疗费用占比,BZ_民政救助,BZ_城乡优抚,是否挂号,RES
8621,352120000000000,0,6,9,7.500000,3,2.666667,47,10,7.833333,2580.54,2077.016667,2733.76,2174.541667,22,15.666667,5909.53,4154.033333,6441.34,4349.083333,3,99,45,1,6,0,1438.15,12462.10,13900.25,1403.94,13047.25,34.21,12993.76,184.62,1237.26,6095.34,289.0,0.0,289.0,0,564.0,0.0,564.0,0,0,0.0,0.0,0.0,0.00,0.0,0.00,0,0.0,0,0.00,0.0,1384.66,0.0,0.0,12462.10,0.0,0.00,196.00,1242.15,13846.76,0.0,0.0,0.0,0.00,0.0,6,22.0,0.938634,0.002622,0.020791,0.0,0.040575,0.000000,0,0,0,0
9356,352120000000000,0,6,7,5.000000,3,2.333333,32,8,5.333333,6736.14,3969.165000,7086.77,4135.130000,22,10.666667,18515.63,7938.330000,18356.08,8270.260000,3,77,30,1,6,0,9430.95,23814.99,33245.94,6390.46,24810.78,20.89,24693.21,7043.01,8129.46,8606.95,4396.0,0.0,4056.0,1785,537.5,2.0,535.5,0,0,0.0,4.0,0.0,3497.66,3000.0,3013.60,0,0.0,0,484.06,0.0,5953.78,0.0,0.0,23814.99,0.0,0.00,116.00,9314.95,29768.77,0.0,0.0,0.0,0.00,0.0,2,3.0,0.746280,0.000842,0.132227,0.0,0.016167,0.003721,0,0,1,0
8441,352120000000000,0,6,3,2.166667,1,1.000000,13,3,2.166667,3943.57,2533.601667,4710.81,3085.598333,13,13.000000,15201.61,15201.610000,18513.59,18513.590000,1,44,13,1,6,0,4002.88,15201.61,19204.49,3956.39,18513.59,29.59,18334.05,1499.50,2487.90,0.00,570.0,0.0,564.0,120,95.0,0.0,95.0,0,0,0.0,0.0,0.0,25.90,0.0,16.90,0,0.0,0,9.00,0.0,3800.44,0.0,0.0,15201.61,0.0,0.00,0.00,4002.88,19002.05,0.0,0.0,0.0,0.00,0.0,3,40.0,0.964024,0.001598,0.029681,0.0,0.004947,0.000000,0,0,1,0
6523,352120000000000,0,5,2,1.600000,1,1.000000,8,2,1.600000,4138.15,2945.196000,3635.56,2408.380000,8,8.000000,14725.98,14725.980000,12041.90,12041.900000,1,68,8,1,5,0,2064.62,14725.98,16790.60,2047.88,12041.90,3.86,11846.72,1634.00,4344.99,0.00,4146.5,0.0,3926.2,1548,176.0,0.0,176.0,0,0,0.0,0.0,0.0,426.20,0.0,12.88,0,0.0,0,413.32,0.0,1636.26,0.0,0.0,14725.98,0.0,0.00,0.00,2064.62,16362.24,0.0,0.0,0.0,0.00,0.0,2,13.0,0.717181,0.000321,0.246954,0.0,0.010482,0.000000,0,0,1,0
10891,352120000000000,0,6,3,3.000000,2,2.000000,18,3,3.000000,2128.54,1891.123333,2151.26,1988.118333,12,9.000000,6609.60,5673.370000,6702.77,5964.355000,2,36,18,1,6,0,1260.71,11346.74,12607.45,1260.71,11928.71,0.00,11928.71,0.00,3117.44,0.00,113.0,0.0,113.0,0,119.0,0.0,119.0,0,0,0.0,0.0,0.0,446.74,0.0,0.00,0,0.0,0,446.74,0.0,1260.71,0.0,0.0,11346.74,0.0,0.00,0.00,1260.71,12607.45,0.0,0.0,0.0,0.00,0.0,4,38.0,0.946164,0.000000,0.008963,0.0,0.009439,0.000000,0,0,0,0
11899,352120000000000,0,4,2,1.750000,1,1.000000,7,2,1.750000,1335.41,809.695000,1382.50,694.755000,7,7.000000,3238.78,3238.780000,2779.02,2779.020000,1,14,7,1,4,0,359.88,3238.78,3598.66,359.88,2779.02,0.00,2779.02,0.00,0.00,2779.02,229.0,0.0,229.0,0,128.0,0.0,128.0,0,0,0.0,0.0,0.0,462.64,0.0,0.00,0,0.0,0,462.64,0.0,359.88,0.0,0.0,3238.78,0.0,0.00,0.00,359.88,3598.66,0.0,0.0,0.0,0.00,0.0,0,NaN,0.772237,0.000000,0.063635,0.0,0.035569,0.000000,0,0,0,0
8038,352120000000000,26,6,17,14.000000,5,3.500000,111,27,18.500000,10000.60,6213.303333,11201.27,7449.608333,58,22.200000,17786.02,7455.964000,21670.42,8939.530000,5,220,84,1,6,0,8777.05,37279.82,46056.87,8691.73,44697.65,85.32,44061.59,7599.38,15205.15,579.60,558.0,0.0,558.0,0,681.5,0.0,681.5,0,0,0.0,0.0,0.0,119.72,0.0,0.00,0,0.0,0,119.72,0.0,8140.99,0.0,0.0,37279.82,0.0,0.00,0.00,8777.05,45420.81,0.0,0.0,0.0,0.00,0.0,10,27.0,0.970488,0.001909,0.012115,0.0,0.014797,0.000000,0,0,0,0
14986,352121000000000,9,6,7,4.666667,3,2.833333,38,9,6.333333,3526.37,2981.428333,3800.20,3058.025000,13,12.666667,8139.88,5962.856667,8074.23,6116.050000,3,79,28,1,6,0,2451.28,17888.57,20339.85,1987.68,18348.15,56.00,18292.15,0.00,6909.57,7038.06,890.0,0.0,890.0,0,1065.0,378.0,687.0,0,0,0.0,0.0,0.0,30.10,0.0,23.00,0,6.6,0,7.10,0.0,1987.68,0.0,0.0,17888.57,0.0,0.00,0.00,2451.28,19876.25,0.0,0.0,0.0,0.00,0.0,10,26.0,0.902079,0.003052,0.043756,0.0,0.052360,0.354930,0,0,0,0
7947,352120000000000,0,6,5,3.166667,2,1.166667,20,6,3.333333,2618.18,1766.705000,2948.78,1928.801667,18,10.000000,9267.67,5300.115000,10024.09,5786.405000,2,54,19,1,6,0,1881.98,10600.23,12482.21,1870.62,11572.81,0.36,11572.45,3544.60,465.64,1384.04,108.0,0.0,108.0,0,389.0,11.0,378.0,0,0,0.0,0.0,0.0,412.40,0.0,0.00,0,0.0,0,412.40,0.0,1870.62,0.0,0.0,10600.23,0.0,0.00,347.14,1534.84,12470.85,0.0,0.0,0.0,0.00,0.0,5,38.0,0.927144,0.000031,0.008652,0.0,0.031164,0.028278,0,0,1,0
1955,352120000000000,10,6,10,9.333333,3,2.166667,67,14,11.166667,9375.24,8486.815000,8271.27,7224.883333,52,22.333333,46322.27,16973.630000,38952.56,14449.766670,3,248,56,1,6,0,3451.64,50920.89,49728.80,3095.87,43349.30,329.97,42877.45,3018.66,6645.97,22068.83,5151.0,0.0,5151.0,0,654.9,2.4,652.5,0,0,0.0,0.0,0.0,550.20,0.0,0.00,0,23.4,0,550.20,0.0,7597.72,0.0,0.0,41633.43,0.0,4643.73,222.76,3228.88,49231.15,7739.6,0.0,0.0,4643.73,0.0,8,22.0,0.871714,0.007612,0.103582,0.0,0.013169,0.003665,1,0,0,1

随机抽样10行数据进行检查，符合“每列是一个变量，每行是一个观察值，每个单元格是一个值”，具体来看每行表示一个患者全部的就诊信息，每列是就诊相关的各个变量，包括就诊次数，付费等，因此不存在结构性问题

### 评估数据干净度

In [78]:
ori_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 82 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   个人编码               16000 non-null  int64
 1   一天去两家医院的天数         16000 non-null  int64
 2   就诊的月数              16000 non-null  int64
 3   月就诊天数_MAX          16000 non-null  int64
 4   月就诊天数_AVG          16000 non-null  float64
 5   月就诊医院数_MAX         16000 non-null  int64
 6   月就诊医院数_AVG         16000 non-null  float64
 7   就诊次数_SUM           16000 non-null  int64
 8   月就诊次数_MAX          16000 non-null  int64
 9   月就诊次数_AVG          16000 non-null  float64
 10  月统筹金额_MAX          16000 non-null  float64
 11  月统筹金额_AVG          16000 non-null  float64
 12  月药品金额_MAX          16000 non-null  float64
 13  月药品金额_AVG          16000 non-null  float64
 14  医院_就诊天数_MAX        16000 non-null  int64
 15  医院_就诊天数_AVG        16000 non-null  float64
 16  医院_统筹金_MAX         16000 non-null  float64
 17  医院_统筹金_AVG         16000 non-null  float64
 18  医院_药品_MAX          16000 non-null  float64
 19  医院_药品_AVG          16000 non-null  float64
 20  医院编码_NN            16000 non-null  int64
 21  顺序号_NN             16000 non-null  int64
 22  交易时间DD_NN          16000 non-null  int64
 23  交易时间YYYY_NN        16000 non-null  int64
 24  交易时间YYYYMM_NN      16000 non-null  int64
 25  住院天数_SUM           16000 non-null  int64
 26  个人账户金额_SUM         16000 non-null  float64
 27  统筹支付金额_SUM         16000 non-null  float64
 28  ALL_SUM            16000 non-null  float64
 29  可用账户报销金额_SUM       16000 non-null  float64
 30  药品费发生金额_SUM        16000 non-null  float64
 31  药品费自费金额_SUM        16000 non-null  float64
 32  药品费申报金额_SUM        16000 non-null  float64
 33  贵重药品发生金额_SUM       16000 non-null  float64
 34  中成药费发生金额_SUM       16000 non-null  float64
 35  中草药费发生金额_SUM       16000 non-null  float64
 36  检查费发生金额_SUM        16000 non-null  float64
 37  检查费自费金额_SUM        16000 non-null  float64
 38  检查费申报金额_SUM        16000 non-null  float64
 39  贵重检查费金额_SUM        16000 non-null  int64
 40  治疗费发生金额_SUM        16000 non-null  float64
 41  治疗费自费金额_SUM        16000 non-null  float64
 42  治疗费申报金额_SUM        16000 non-null  float64
 43  手术费发生金额_SUM        16000 non-null  int64
 44  手术费自费金额_SUM        16000 non-null  int64
 45  手术费申报金额_SUM        16000 non-null  float64
 46  床位费发生金额_SUM        16000 non-null  float64
 47  床位费申报金额_SUM        16000 non-null  float64
 48  医用材料发生金额_SUM       16000 non-null  float64
 49  高价材料发生金额_SUM       16000 non-null  float64
 50  医用材料费自费金额_SUM      16000 non-null  float64
 51  成分输血申报金额_SUM       16000 non-null  int64
 52  其它发生金额_SUM         16000 non-null  float64
 53  其它申报金额_SUM         16000 non-null  int64
 54  一次性医用材料申报金额_SUM    16000 non-null  float64
 55  起付线标准金额_MAX        16000 non-null  float64
 56  起付标准以上自负比例金额_SUM   16000 non-null  float64
 57  医疗救助个人按比例负担金额_SUM  16000 non-null  float64
 58  最高限额以上金额_SUM       16000 non-null  float64
 59  基本统筹基金支付金额_SUM     16000 non-null  float64
 60  公务员医疗补助基金支付金额_SUM  16000 non-null  float64
 61  城乡救助补助金额_SUM       16000 non-null  float64
 62  基本个人账户支付_SUM       16000 non-null  float64
 63  非账户支付金额_SUM        16000 non-null  float64
 64  本次审批金额_SUM         16000 non-null  float64
 65  补助审批金额_SUM         16000 non-null  float64
 66  医疗救助医院申请_SUM       16000 non-null  float64
 67  残疾军人补助_SUM         16000 non-null  float64
 68  民政救助补助_SUM         16000 non-null  float64
 69  城乡优抚补助_SUM         16000 non-null  float64
 70  出院诊断病种名称_NN        16000 non-null  int64
 71  出院诊断LENTH_MAX      15645 non-null  float64
 72  药品在总金额中的占比         16000 non-null  float64
 73  个人支付的药品占比          16000 non-null  float64
 74  检查总费用在总金额占比        16000 non-null  float64
 75  个人支付检查费用占比         16000 non-null  float64
 76  治疗费用在总金额占比         16000 non-null  float64
 77  个人支付治疗费用占比         16000 non-null  float64
 78  BZ_民政救助            16000 non-null  int64
 79  BZ_城乡优抚            16000 non-null  int64
 80  是否挂号               16000 non-null  int64
 81  RES                16000 non-null  int64
dtypes: float64(58), int64(24)
memory usage: 10.0 MB

- 第71个特征：住院诊断LENTH_MAX 存在缺失值
- 第0个特征：个人编码全部一样，可以删除
- 第1~19个特征：天数、次数、金额等，确实为数值变量，且分布较均匀，该部分特征初步判断无较大问题
- 第20个特征：医院编码_NN 应为分类变量，这里为int64数值类型
- 第21-24个特征：顺序号_NN，交易时间DD_NN，交易时间YYYY_NN，交易时间YYYYMM_NN这四个特征经过脱敏处理后没有特殊意义，对后续模型建立无较大影响，可以删除
- 医院编码_NN、顺序号_NN，交易时间DD_NN，交易时间YYYY_NN，交易时间YYYYMM_NN均为抽取的其中一次交易记录
- 第25个特征：住院天数_SUM，全为0，可以删除
- 第26~80个特征：为各种支付金额，存在较大相关性。其中70出院诊断病种名称应为分类变量，71出院诊断LENTH_MAX脱敏处理后无实际意义，对后续模型建立无较大影响，可以删除；78 BZ_民政救助、79 BZ_城乡优抚、 80 是否挂号 应为分类变量；
- 第81个特征：欺诈结果，为1则表示欺诈

- 总体来说只有第1~19和26~80等特征具有实际意义，对模型构建影响较大，且之中存在较强相关性，需要谨慎处理
- 个人编码，顺序号_NN，交易时间DD_NN，交易时间YYYY_NN，交易时间YYYYMM_NN这5个特征脱敏处理后无实际意义，对模型构建无较大影响，可以直接删除
- 医院编码_NN不太确定是否可以忽略，但是应该与上文顺序号，交易时间等类似，为抽取的其中一次记录；有研究发现医院等级和欺诈有关，等级越高，欺诈越低，应该保留
- 出院诊断病种名称、民政救助、城乡优抚、是否挂号为分类变量，应进行独热编码

经过上述对数据的初步分析，有3个待做事项
1. 删除一些无意义特征
2. 对分类变量进行独热编码
3. 某些特征重复较大，需要进行低方差滤波，但是阈值需要谨慎考虑

- 对于缺失数据，无效，可以直接删除
- 需要查看是否存在重复数据
- 特征绝大数为数值型数据，不存在数据不一致现象
- 需要查看是否存在无效或错误数据

#### 查看是否存在重复数据

In [79]:
ori_data.duplicated().sum()

1

In [80]:
ori_data[ori_data.duplicated(keep=False)]

,个人编码,一天去两家医院的天数,就诊的月数,月就诊天数_MAX,月就诊天数_AVG,月就诊医院数_MAX,月就诊医院数_AVG,就诊次数_SUM,月就诊次数_MAX,月就诊次数_AVG,月统筹金额_MAX,月统筹金额_AVG,月药品金额_MAX,月药品金额_AVG,医院_就诊天数_MAX,医院_就诊天数_AVG,医院_统筹金_MAX,医院_统筹金_AVG,医院_药品_MAX,医院_药品_AVG,医院编码_NN,顺序号_NN,交易时间DD_NN,交易时间YYYY_NN,交易时间YYYYMM_NN,住院天数_SUM,个人账户金额_SUM,统筹支付金额_SUM,ALL_SUM,可用账户报销金额_SUM,药品费发生金额_SUM,药品费自费金额_SUM,药品费申报金额_SUM,贵重药品发生金额_SUM,中成药费发生金额_SUM,中草药费发生金额_SUM,检查费发生金额_SUM,检查费自费金额_SUM,检查费申报金额_SUM,贵重检查费金额_SUM,治疗费发生金额_SUM,治疗费自费金额_SUM,治疗费申报金额_SUM,手术费发生金额_SUM,手术费自费金额_SUM,手术费申报金额_SUM,床位费发生金额_SUM,床位费申报金额_SUM,医用材料发生金额_SUM,高价材料发生金额_SUM,医用材料费自费金额_SUM,成分输血申报金额_SUM,其它发生金额_SUM,其它申报金额_SUM,一次性医用材料申报金额_SUM,起付线标准金额_MAX,起付标准以上自负比例金额_SUM,医疗救助个人按比例负担金额_SUM,最高限额以上金额_SUM,基本统筹基金支付金额_SUM,公务员医疗补助基金支付金额_SUM,城乡救助补助金额_SUM,基本个人账户支付_SUM,非账户支付金额_SUM,本次审批金额_SUM,补助审批金额_SUM,医疗救助医院申请_SUM,残疾军人补助_SUM,民政救助补助_SUM,城乡优抚补助_SUM,出院诊断病种名称_NN,出院诊断LENTH_MAX,药品在总金额中的占比,个人支付的药品占比,检查总费用在总金额占比,个人支付检查费用占比,治疗费用在总金额占比,个人支付治疗费用占比,BZ_民政救助,BZ_城乡优抚,是否挂号,RES
1322,352120000000000,0,1,1,1.0,1,1.0,1,1,1.0,248.9,248.9,0.0,0.0,1,1.0,248.9,248.9,0.0,0.0,1,2,1,1,1,0,27.66,248.9,276.56,27.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,17.0,0.0,17.0,0,0,0.0,0.0,0.0,259.56,0.0,0.0,0,0.0,0,259.56,0.0,27.66,0.0,0.0,248.9,0.0,0.0,0.0,27.66,276.56,0.0,0.0,0.0,0.0,0.0,0,NaN,0.0,0.0,0.0,0.0,0.061469,0.0,0,0,0,0
3518,352120000000000,0,1,1,1.0,1,1.0,1,1,1.0,248.9,248.9,0.0,0.0,1,1.0,248.9,248.9,0.0,0.0,1,2,1,1,1,0,27.66,248.9,276.56,27.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,17.0,0.0,17.0,0,0,0.0,0.0,0.0,259.56,0.0,0.0,0,0.0,0,259.56,0.0,27.66,0.0,0.0,248.9,0.0,0.0,0.0,27.66,276.56,0.0,0.0,0.0,0.0,0.0,0,NaN,0.0,0.0,0.0,0.0,0.061469,0.0,0,0,0,0

由上述输出可得，存在一行重复数据，1322和3518重复，我们保留前面一行即可

#### 查看是否存在无效数据或错误数据

In [81]:
ori_data.describe()

,个人编码,一天去两家医院的天数,就诊的月数,月就诊天数_MAX,月就诊天数_AVG,月就诊医院数_MAX,月就诊医院数_AVG,就诊次数_SUM,月就诊次数_MAX,月就诊次数_AVG,月统筹金额_MAX,月统筹金额_AVG,月药品金额_MAX,月药品金额_AVG,医院_就诊天数_MAX,医院_就诊天数_AVG,医院_统筹金_MAX,医院_统筹金_AVG,医院_药品_MAX,医院_药品_AVG,医院编码_NN,顺序号_NN,交易时间DD_NN,交易时间YYYY_NN,交易时间YYYYMM_NN,住院天数_SUM,个人账户金额_SUM,统筹支付金额_SUM,ALL_SUM,可用账户报销金额_SUM,药品费发生金额_SUM,药品费自费金额_SUM,药品费申报金额_SUM,贵重药品发生金额_SUM,中成药费发生金额_SUM,中草药费发生金额_SUM,检查费发生金额_SUM,检查费自费金额_SUM,检查费申报金额_SUM,贵重检查费金额_SUM,治疗费发生金额_SUM,治疗费自费金额_SUM,治疗费申报金额_SUM,手术费发生金额_SUM,手术费自费金额_SUM,手术费申报金额_SUM,床位费发生金额_SUM,床位费申报金额_SUM,医用材料发生金额_SUM,高价材料发生金额_SUM,医用材料费自费金额_SUM,成分输血申报金额_SUM,其它发生金额_SUM,其它申报金额_SUM,一次性医用材料申报金额_SUM,起付线标准金额_MAX,起付标准以上自负比例金额_SUM,医疗救助个人按比例负担金额_SUM,最高限额以上金额_SUM,基本统筹基金支付金额_SUM,公务员医疗补助基金支付金额_SUM,城乡救助补助金额_SUM,基本个人账户支付_SUM,非账户支付金额_SUM,本次审批金额_SUM,补助审批金额_SUM,医疗救助医院申请_SUM,残疾军人补助_SUM,民政救助补助_SUM,城乡优抚补助_SUM,出院诊断病种名称_NN,出院诊断LENTH_MAX,药品在总金额中的占比,个人支付的药品占比,检查总费用在总金额占比,个人支付检查费用占比,治疗费用在总金额占比,个人支付治疗费用占比,BZ_民政救助,BZ_城乡优抚,是否挂号,RES
count,1.600000e+04,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.0,16000.000000,16000.0,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,15645.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000
mean,3.521202e+14,1.883875,5.817812,7.824438,5.854813,2.099000,1.735954,36.818438,8.419250,6.264291,3943.185445,2783.040791,3631.380422,2602.861947,26.638500,19.079701,12602.672037,9056.441440,11696.530186,8257.661369,2.197500,91.459750,34.419375,1.0,5.817812,0.0,2318.743704,16248.157033,18581.903839,2200.475267,15275.711085,80.603902,15023.718634,2709.672334,3401.571010,2389.157068,598.063251,10.267001,580.508156,60.580062,2385.897406,8.733015,2348.499072,7.891188,0.090000,7.800469,5.195688,5.150125,301.377911,17.197364,10.763950,10.078250,7.767312,0.048625,263.894079,7.405927,2315.785588,101.078898,0.079136,15440.051715,51.805779,377.007672,126.748913,2191.994791,18236.173922,572.439964,404.379674,3.618437,374.437024,1.236406,5.343438,26.032279,0.854763,0.005500,0.039006,0.005560,0.081316,0.010609,0.143125,0.000562,0.253250,0.049563
std,7.769642e+08,5.227365,0.702069,4.193234,3.377273,0.947038,0.724497,23.656539,5.199283,3.940291,2936.217833,1857.794225,2682.941527,1776.066792,17.587198,14.173003,9507.692019,8318.767632,8555.770743,6948.782110,1.048302,64.978792,20.400236,0.0,0.702069,0.0,2427.725593,10696.643485,13507.065808,2369.065418,10536.443992,215.586310,10240.500007,6256.166307,3818.560983,3333.948935,908.926822,88.452731,855.831610,308.040347,7070.959992,94.206063,6940.260261,162.875183,5.830707,162.763860,30.771234,30.710988,520.176901,427.518396,100.977949,443.899162,29.998053,3.263327,474.467387,111.156022,2253.697641,1140.931780,10.010032,9016.969096,514.786578,1670.137464,204.646380,2415.539590,13107.096667,2295.805737,4563.731157,212.888960,1660.898502,78.017209,2.889941,12.353055,0.168843,0.013990,0.064466,0.032765,0.155653,0.056906,0.350211,0.023711,0.434886,0.217046
min,3.521200e+14,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.0,1.000000,0.0,1.450000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.521200e+14,0.000000,6.000000,5.000000,3.500000,1.000000,1.000000,22.000000,5.000000,3.666667,2420.145000,1793.384583,2351.600000,1751.854583,14.000000,10.666667,7624.852500,4730.801250,7449.155000,4583.521250,1.000000,54.000000,21.000000,1.0,6.000000,0.0,1208.200000,10555.920000,11901.582500,1142.730000,10313.175000,0.040000,10190.357500,0.000000,1440.892500,0.000000,18.000000,0.000000,18.000000,0.000000,216.000000,0.000000,213.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.890000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1223.840000,0.000000,0.000000,10407.455000,0.000000,0.000000,0.000000,1090.832500,11742.340000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,17.000000,0.845445,0.000003,0.001170,0.000000,0.015839,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.521200e+14,0.000000,6.000000,7.000000,5.166667,2.000000,1.666667,32.000000,7.000000,5.333333,3125.405000,2255.458333,3001.875000,2184.220833,23.000000,15.000000,10279.710000,6562.982500,10104.070000,6364.521667,2.000000,78.000000,30.000000,1.0,6.000000,0.0,1629.650000,13303.175000,14868.435000,1530.875000,12876.790000,8.250000,12740.265000,1094.870000,2703.155000,537.515000,273.000000,0.000000,271.000000,0.000000,401.000000,0.000000,394.000000,0.000000,0.000000,0.000000,0.000000,0.000000,177.940000,0.000000,0.000000,0.000000,0.000000,0.000000,123.100000,0.000000,1594.130000,0.000000,0.000000,13035.855000,0.000000,0.000000,104.575000,1506.365000,14676.875000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,25.000000,0.907803,0.000569,0.016690,0.000000,0.027925,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.521200e+14,0.000000,6.000000,10.000000,7.333333,3.000000,2.000000,46.000000,10.000000,7.833333,4464.017500,3135.721667,4119.525000,2948.170000,33.000000,23.000000,13993.330000,10622.245000,13465.987500,10196.982500,3.000000,110.000000,43.000000,1.0,6.000000,0.0,2445.572500,18474.095000,20599.815000,2295.292500,17441.580000,67.642500,17189.670000,2893.660000,4280.675000,4180.015000,783.000000,0.000000,771.000000,0.000000,807.000000,0.000000,791.625000,0.000000,0.000000,0.000000,0.000000,0.000000,464.800000,0.000000,0.000000,0.000000,6.000000,0.000000,439.365000,0.000000,2346.115000,0.000000,0.000000,17851.357500,0.000000,0.000000,165.217500,2310.055000,20275.970000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,34.000000,0.946247,0.004818,0.049281,0.000000,0.051846,0.000000,0.000000,0.000000,1.000000,0.000000
max,3.521280e+14,108.000000,7.000000,31.000000,30.000000,8.000000,7.000000,307.000000,75.000000,51.166667,44590.330000,37403.050000,77841.700000,38656.056670,180.000000,172.000000,100726.770000,100726.770000,203167.880000,151598.250000,9.000000,1415.000000,180.000000,1.0,7.000000,0.0,45518.610000,125861.490000,240320.340000,45518.580000,231936.340000,11165.130000,224594.610000,189729.700000,115738.150000,34412.120000,13941.000000,3864.000000,10685.400000,7670.000000,52120.000000,7750.000000,51087.800000,7975.000000,600.000000,7975.000000,795.000000,795.000000,31303.100000,31270.800000,4154.100000,39718.000000,750.000000,375.000000,28257.540000,3638.480000,23643.030000,39457.270000,1266.180000,117786.270000,18465.360000,43123.200000,8297.080000,45345.100000,232978.610000,53903.790000,157830.320000,16965.630000,43123.200000,8913.440000,39.000000,86.000000,1.000000,0.689375,0.962401,1.000000,1.000000,0.883652,1.000000,1.000000,1.000000,1.000000

由上述输出，不存在无效数据或错误数据

### 总结

1. 删除无意义特征，个人编码，顺序号_NN，交易时间DD_NN，交易时间YYYY_NN，交易时间YYYYMM_NN
2. 删除重复数据
3. 出院诊断LENTH_MAX存在缺失值，需要进行填补
4. 某些特征重复较大，需要进行低方差滤波，但是阈值需要谨慎考虑
5. 对数值变量进行标准化处理，减小变量取值范围相差较大的影响
6. 医院编码_NN，出院诊断病种名称、民政救助、城乡优抚、是否挂号为分类变量，应进行独热编码

# 清洗数据

## 删除无意义特征

In [82]:
clean_data = ori_data.drop(columns=['个人编码','顺序号_NN','交易时间DD_NN','交易时间YYYY_NN','交易时间YYYYMM_NN'])
print(clean_data.shape)
print(ori_data.shape)

(16000, 77)
(16000, 82)

## 删除重复数据

In [83]:
clean_data.drop_duplicates(inplace=True)
clean_data.reset_index(drop=True, inplace=True)
clean_data.shape

(15999, 77)

## 缺失值处理

In [84]:
clean_data['出院诊断LENTH_MAX'].describe()

count    15645.000000
mean        26.032279
std         12.353055
min          2.000000
25%         17.000000
50%         25.000000
75%         34.000000
max         86.000000
Name: 出院诊断LENTH_MAX, dtype: float64

In [85]:
from sklearn.impute import SimpleImputer
lenth_max = clean_data.loc[:, "出院诊断LENTH_MAX"].values.reshape(-1, 1)
clean_data['出院诊断LENTH_MAX'].values
imp_median = SimpleImputer(strategy='median')
imp_median = imp_median.fit_transform(lenth_max)
clean_data.loc[:, "出院诊断LENTH_MAX"] = imp_median

## 独热编码

In [86]:
from sklearn.preprocessing import OneHotEncoder
X_onehot = clean_data.loc[:, ["医院编码_NN", "出院诊断病种名称_NN"]]
enc = OneHotEncoder(categories='auto').fit(X_onehot)
result_onehot = enc.transform(X_onehot).toarray()
feature_name = enc.get_feature_names_out()
data_onehot = pd.DataFrame(result_onehot, columns=feature_name)
newdata = pd.concat([clean_data, data_onehot],axis=1)
newdata.drop(columns=["医院编码_NN", "出院诊断病种名称_NN"], inplace=True)

## 归一化

In [87]:
from sklearn.preprocessing import MinMaxScaler
data_minmax = pd.DataFrame(MinMaxScaler().fit_transform(newdata),columns = newdata.columns )
# 将要移动的列使用pop方法取出，然后放到最后
res = data_minmax.pop('RES')

# 重新创建DataFrame，并将取出的列作为最后一列
data_minmax = pd.concat(
    [data_minmax, pd.DataFrame(res, columns=["RES"])], axis=1)
data_minmax.head()

,一天去两家医院的天数,就诊的月数,月就诊天数_MAX,月就诊天数_AVG,月就诊医院数_MAX,月就诊医院数_AVG,就诊次数_SUM,月就诊次数_MAX,月就诊次数_AVG,月统筹金额_MAX,月统筹金额_AVG,月药品金额_MAX,月药品金额_AVG,医院_就诊天数_MAX,医院_就诊天数_AVG,医院_统筹金_MAX,医院_统筹金_AVG,医院_药品_MAX,医院_药品_AVG,住院天数_SUM,个人账户金额_SUM,统筹支付金额_SUM,ALL_SUM,可用账户报销金额_SUM,药品费发生金额_SUM,药品费自费金额_SUM,药品费申报金额_SUM,贵重药品发生金额_SUM,中成药费发生金额_SUM,中草药费发生金额_SUM,检查费发生金额_SUM,检查费自费金额_SUM,检查费申报金额_SUM,贵重检查费金额_SUM,治疗费发生金额_SUM,治疗费自费金额_SUM,治疗费申报金额_SUM,手术费发生金额_SUM,手术费自费金额_SUM,手术费申报金额_SUM,床位费发生金额_SUM,...,是否挂号,医院编码_NN_1,医院编码_NN_2,医院编码_NN_3,医院编码_NN_4,医院编码_NN_5,医院编码_NN_6,医院编码_NN_7,医院编码_NN_8,医院编码_NN_9,出院诊断病种名称_NN_0,出院诊断病种名称_NN_1,出院诊断病种名称_NN_2,出院诊断病种名称_NN_3,出院诊断病种名称_NN_4,出院诊断病种名称_NN_5,出院诊断病种名称_NN_6,出院诊断病种名称_NN_7,出院诊断病种名称_NN_8,出院诊断病种名称_NN_9,出院诊断病种名称_NN_10,出院诊断病种名称_NN_11,出院诊断病种名称_NN_12,出院诊断病种名称_NN_13,出院诊断病种名称_NN_14,出院诊断病种名称_NN_15,出院诊断病种名称_NN_16,出院诊断病种名称_NN_17,出院诊断病种名称_NN_18,出院诊断病种名称_NN_19,出院诊断病种名称_NN_20,出院诊断病种名称_NN_21,出院诊断病种名称_NN_22,出院诊断病种名称_NN_23,出院诊断病种名称_NN_24,出院诊断病种名称_NN_25,出院诊断病种名称_NN_28,出院诊断病种名称_NN_32,出院诊断病种名称_NN_34,出院诊断病种名称_NN_39,RES
0,0.000000,0.833333,0.200000,0.160920,0.285714,0.194444,0.107843,0.081081,0.093023,0.078519,0.067943,0.050120,0.069725,0.106145,0.060429,0.074985,0.050459,0.041948,0.035558,0.0,0.043270,0.121147,0.071634,0.041040,0.069725,0.006174,0.070924,0.010460,0.041270,0.0,0.062765,0.0,0.081887,0.0,0.002456,0.0,0.002505,0.0,0.0,0.0,0.00000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.833333,0.100000,0.051724,0.142857,0.055556,0.045752,0.040541,0.029900,0.049734,0.043776,0.031463,0.046129,0.067039,0.038012,0.094315,0.048766,0.050744,0.035287,0.0,0.030101,0.078055,0.046571,0.029431,0.046129,0.002857,0.046390,0.011937,0.009785,0.0,0.024747,0.0,0.032287,0.0,0.002878,0.0,0.002936,0.0,0.0,0.0,0.00000,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.074074,0.833333,0.233333,0.178161,0.285714,0.194444,0.143791,0.108108,0.129568,0.075365,0.069060,0.042420,0.061272,0.122905,0.081871,0.090956,0.051288,0.052964,0.031247,0.0,0.057907,0.123138,0.075449,0.057587,0.061272,0.000423,0.062009,0.000000,0.032506,0.0,0.000000,0.0,0.000000,0.0,0.067882,0.0,0.069253,0.0,0.0,0.0,0.09434,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.833333,0.166667,0.091954,0.142857,0.138889,0.071895,0.067568,0.056478,0.067966,0.055015,0.019271,0.027130,0.089385,0.061404,0.115383,0.061286,0.027094,0.020753,0.0,0.030134,0.098095,0.057072,0.030139,0.027130,0.000104,0.028011,0.000000,0.043856,0.0,0.000000,0.0,0.000000,0.0,0.142498,0.0,0.145377,0.0,0.0,0.0,0.00000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.833333,0.133333,0.114943,0.000000,0.000000,0.081699,0.054054,0.066445,0.052308,0.058720,0.032929,0.062550,0.139665,0.146199,0.130828,0.130828,0.071407,0.095697,0.0,0.034453,0.104702,0.061351,0.034383,0.062550,0.000411,0.064125,0.012479,0.031785,0.0,0.000000,0.0,0.000000,0.0,0.004605,0.0,0.004698,0.0,0.0,0.0,0.00000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 低方差滤波

In [88]:
var = data_minmax.var()
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()  
data_var0 = selector.fit_transform(data_minmax)  # 获取删除不合格特征之后的新特征矩阵
minmax_columns = data_minmax.columns
data_var0_df = pd.DataFrame(
    data_var0, columns=minmax_columns[selector.get_support(indices=True)])

通过低方差滤波过滤掉了方差为0的特征 住院天数

## 互信息法

In [89]:
from sklearn.feature_selection import mutual_info_classif as MIC
X_0 = data_var0_df.iloc[:,:-1]
y = data_var0_df.iloc[:,-1]
result = MIC(X_0, y,random_state=0)
k = result.shape[0] - sum(result <= 0)
data_var0_columns = data_var0_df.iloc[:, :-1].columns
data_mic_df = pd.DataFrame(
    X_0.iloc[:, result > 0], columns=data_var0_columns[result > 0]
)
X_mic = X_0.iloc[:, result > 0]
data_mic_df["RES"] = y
# data_mic_df.to_excel('data_预处理1.xlsx', index=False)

# PCA

In [90]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

X = data_mic_df.iloc[:, :62]
Y = data_mic_df.iloc[:, -1]
X_s = data_mic_df.iloc[:, 62:-1]
pca = PCA(12).fit(X)
X_final = pca.fit_transform(X)
columns = [*(f'主成分{i}' for i in range(1, 13))]
df = pd.DataFrame(X_final, columns=[*(f'主成分{i}' for i in range(1, 13))])
df_final = pd.concat([df, data_mic_df.iloc[:, 62:]], axis=1)
df_minmax = pd.DataFrame(MinMaxScaler().fit_transform(
    df_final), columns=df_final.columns)
df_minmax.to_excel('data_handle.xlsx', index=False)